# Generated by Django 4.2.6 on 2023-11-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnapPulse', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='SnapPulse.comments'),
        ),
    ]
