# Generated by Django 4.2.6 on 2023-11-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SnapPulse', '0004_reels_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='reels',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='messages',
            field=models.ManyToManyField(to='SnapPulse.message'),
        ),
        migrations.AddField(
            model_name='reels',
            name='messages',
            field=models.ManyToManyField(to='SnapPulse.message'),
        ),
    ]
